import { chromium } from '@playwright/test';
const S = process.env.SCRATCH;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 720 }, recordVideo: { dir: S + '/video2', size: { width: 1280, height: 720 } } });
const page = await ctx.newPage();
await page.goto('http://localhost:4173');
await page.waitForSelector('.loader[data-done="true"]', { timeout: 120000 });
await page.waitForFunction(() => { const s = window.__frameLoadState; return s && s.loaded >= s.total; }, undefined, { timeout: 120000 });
await page.waitForTimeout(800);
await page.evaluate(() => {
  const track = document.querySelector('.dive-track');
  const max = track.offsetTop + track.offsetHeight - innerHeight;
  window.__lenis.scrollTo(max, { duration: 36, easing: (t) => t });
});
await page.waitForTimeout(37000);
await page.evaluate(() => { window.__lenis.scrollTo(document.body.scrollHeight, { duration: 7 }); });
await page.waitForTimeout(8500);
const video = page.video();
await ctx.close();
console.log('VIDEO:' + (await video.path()));
await browser.close();
