import { chromium } from '@playwright/test';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:4173/');
await page.waitForSelector('.loader[data-done="true"]', { state: 'attached', timeout: 60_000 });
await page.waitForTimeout(600);
await page.screenshot({ path: 'qa/bg-hero.png' });
await page.evaluate(() => document.querySelector('.intro')?.scrollIntoView({ block: 'center' }));
await page.waitForTimeout(1200);
await page.screenshot({ path: 'qa/bg-intro.png' });
await page.evaluate(() => document.querySelector('#specs-title')?.scrollIntoView({ block: 'start' }));
await page.waitForTimeout(1200);
await page.screenshot({ path: 'qa/bg-specs.png' });
await page.evaluate(() => document.querySelector('#kit-title')?.scrollIntoView({ block: 'start' }));
await page.waitForTimeout(1200);
await page.screenshot({ path: 'qa/bg-kit.png' });
await page.evaluate(() => document.querySelector('.footer')?.scrollIntoView({ block: 'end' }));
await page.waitForTimeout(1200);
await page.screenshot({ path: 'qa/bg-footer.png' });
await browser.close();
console.log('done');
