/**
 * The five zones of the dive. Scrolling down IS zooming in:
 * OBJECT (1x) -> DROP -> SPREAD -> BOND -> LATTICE (1,000,000x).
 *
 * Frame ranges live in frame-manifest.json (generated by
 * scripts/extract-frames.sh from the five source clips).
 */

export interface Zone {
  id: string;
  /** HUD label */
  label: string;
  /** Kicker shown above the fact */
  kicker: string;
  /** One striking fact, straight from the datasheet */
  fact: string;
}

export const ZONES: Zone[] = [
  {
    id: 'object',
    label: 'OBJECT',
    kicker: 'The object',
    fact: 'A clear, colourless liquid based on silanes.',
  },
  {
    id: 'drop',
    label: 'DROP',
    kicker: 'The drop',
    fact: '35–50 ml protects an entire car.',
  },
  {
    id: 'spread',
    label: 'SPREAD',
    kicker: 'The spread',
    fact: 'Wipe on. Buff. Cures at ambient temperature.',
  },
  {
    id: 'bond',
    label: 'BOND',
    kicker: 'The bond',
    fact: 'A covalent bond with the paint. It cannot flake off or be washed off.',
  },
  {
    id: 'lattice',
    label: 'LATTICE',
    kicker: 'The lattice',
    fact: 'Hardness up to 9H. Effective for up to 72 months.',
  },
];

/** Magnification runs 1x -> 1,000,000x on a log scale across the dive. */
export const MAG_EXPONENT_MAX = 6;

export function magnificationAt(progress: number): number {
  const p = Math.min(1, Math.max(0, progress));
  return Math.pow(10, p * MAG_EXPONENT_MAX);
}

export function formatMagnification(mag: number): string {
  if (mag < 10) return `${mag.toFixed(1)}×`;
  return `${Math.round(mag).toLocaleString('en-US')}×`;
}
