/**
 * The five zones of the dive. Scrolling down IS zooming in:
 * OBJECT (1x) -> DROP -> SPREAD -> BOND -> LATTICE (1,000,000x).
 *
 * Frame ranges live in frame-manifest.json (generated by
 * scripts/extract-frames.sh from the five source clips).
 */

export interface Zone {
  id: string;
  /** HUD label */
  label: string;
  /** Kicker shown above the fact */
  kicker: string;
  /** One striking fact, straight from the datasheet */
  fact: string;
}

export const ZONES: Zone[] = [
  {
    id: 'object',
    label: 'OBJECT',
    kicker: 'The object',
    fact: 'The molecule that changes everything.',
  },
  {
    id: 'drop',
    label: 'DROP',
    kicker: 'The drop',
    fact: '35–50 ml protects an entire car.',
  },
  {
    id: 'spread',
    label: 'SPREAD',
    kicker: 'The spread',
    fact: 'Wipe on. Buff. Cures at ambient temperature.',
  },
  {
    id: 'bond',
    label: 'BOND',
    kicker: 'The bond',
    fact: 'A covalent bond with the paint. It cannot flake off or be washed off.',
  },
  {
    id: 'lattice',
    label: 'LATTICE',
    kicker: 'The lattice',
    fact: 'Hardness up to 9H. Effective for up to 72 months.',
  },
];

/**
 * Magnification is zone-anchored rather than one blind log sweep:
 * each zone interpolates (log-linearly) between anchors chosen for
 * what its footage plausibly shows — the bottle stays near 1×, the
 * drop reaches tens, the spread hundreds, and only the molecular
 * zones run into microscope territory. Zones are equal fifths of
 * the frame range.
 */
const MAG_ANCHORS = [1, 2, 20, 400, 50_000, 1_000_000];

export function magnificationAt(progress: number): number {
  const p = Math.min(1, Math.max(0, progress));
  const seg = Math.min(ZONES.length - 1, Math.floor(p * ZONES.length));
  const local = p * ZONES.length - seg;
  const a = Math.log10(MAG_ANCHORS[seg]);
  const b = Math.log10(MAG_ANCHORS[seg + 1]);
  return Math.pow(10, a + (b - a) * local);
}

export function formatMagnification(mag: number): string {
  if (mag < 10) return `${mag.toFixed(1)}×`;
  return `${Math.round(mag).toLocaleString('en-US')}×`;
}
